### ISSUE TITLE
Port to 1.21

### ISSUE THREAD

**Issue by Cam396** [mastery3/sharpness6#10]
https://fabricmc.net/2024/05/31/121.html
1.21 Changes many things on the backend and also changes how enchants are structured. Please read the link on the top of this issue to see all of the changes. There are a few fabric api changes that are also mentioned there.

**Comment by mastery3** [comment]
1.21 is still displaying as a release candidate on my end, so I'm gonna wait a little.

**Comment by Cam396** [comment]
1.21 was released and both fabric (https://fabricmc.net/2024/05/31/121.html) and Minecraft (https://feedback.minecraft.net/hc/en-us/articles/27547857163917-Minecraft-Java-Edition-1-21-Tricky-Trials) 
have confirmed that enchants have changed and easier to use with a datapack

**Comment by mastery3** [comment]
There appears to be some problems with the datapack method:

1. I would need to override all Minecraft enchantment files just to change their maximum levels, meaning that a) compatibility with other datapacks that change anything at all about vanilla enchantments is out the window, and b) I would need to copy paste everything from the Minecraft jar data/minecraft/enchantment directory into my mod.
2. Datapacks don't support reading anything in the /config directory, meaning I would have to, at minimum, somehow write something to either dynamically create datapacks, or modify the datapack loader to edit some values (which are both as difficult, if not more so, than the current implementation)

Datapacks seem to be unsuitable for the "change arbitrary enchantment's maximum level to arbitrary values" use case, which is what this mod needs.

**Comment by Cam396** [comment]
hmm ig make a test branch to test stuff to see if it can be used as a mod. just update dependencies and gradle and the simply change the version.

**Comment by mastery3** [comment]
There's a separate issue that somehow no mixins work when trying to update to 1.21.

**Comment by Cam396** [comment]
ok so what do we do then.
do we code a mod that just links the mixins to a datapack or something?

**Comment by mastery3** [comment]
I need to debug that mixin issue before I can create any 1.21 update.

**Comment by Cam396** [comment]
ok is that minecraft wide for all mixins, even things other then enchants, or is it just the mod?

**Comment by mastery3** [comment]
It affects only my mod, but everything in it. Wondering if it's something with gradle.

**Comment by Cam396** [comment]
hmm maybe try updating gradle and dependencies to the latest versions?

**Comment by Cam396** [comment]
oh also they removed basically all of the classes your mod relies on.
1.20.6 
https://maven.fabricmc.net/docs/yarn-1.20.6+build.1/net/minecraft/enchantment/Enchantment.html
1.21
https://maven.fabricmc.net/docs/yarn-1.21+build.1/net/minecraft/enchantment/Enchantment.html
look at the changes between the two, as that is probably why your mod isn't working.

**Comment by mastery3** [comment]
I already figured out why my mixins weren't working (it was what you mentioned, and I additionally got unlucky with the Fabric Example Mixin which is why I thought the whole mod wasn't working).

Good news is that I found the method that would need to be mixined. Bad news is that the method is `RegistryLoader.parseAndAdd`. [Datapack method would be even harder to pull off, so that's not an option]

**Comment by Cam396** [comment]
oh no, i might be able to help but I don't code too much java and js, so you'll have to make a example and then ill be able to do the rest basing it on thee example.

**Comment by Cam396** [comment]
i know enough for what you're doing, but I need to see one example of it first is what I mean

**Comment by mastery3** [comment]
I need to put a mixin in the middle of the `parseAndAdd` function. You're probably going to need to know how to read bytecode to figure this out.

[deleted example just in case I accidentally infringed on copyright]

**Comment by Cam396** [comment]
k i will look at it if i have time

**Comment by mastery3** [comment]
I'll probably just look at [Fabric Mixin Examples](https://fabricmc.net/wiki/tutorial:mixin_examples) to figure it out.

**Comment by mastery3** [comment]
Well, there's a _fourth_ issue: I get a Critical Injection Failure whenever I try to use a `value="INVOKE"`, and only that specific type of mixin. The error message I get in the logs provides no relevant info.

**Comment by Cam396** [comment]
maybe start from scratch with the fabric example project in a new fork?
use gradle 8.8, java 22 GraalVM (if possible, otherwise use java 21) and all latest versions of everything.
sometimes when I'm debugging it is something you wouldn't think of at all, like a old file from a previous version that is somehow affecting it. make a new branch and Ill try to help but I'm going to be somewhere next week.

**Comment by mastery3** [comment]
I had already restarted from fabric example project, so it can't possibly be that.

**Comment by mastery3** [comment]
I did some crazy hack to get the mixin working correctly. I'm creating a github branch right now.

**Comment by Cam396** [comment]
ok got it i will test it on my server

**Comment by Cam396** [comment]
have you pushed the hack yet?

**Comment by mastery3** [comment]
I pushed 1.21 as a new branch.

**Comment by Cam396** [comment]
alright nice now it just needs to be cleaned up a bit and the readme and stuff needs to be fixed

**Comment by mastery3** [comment]
A lot of stuff needs to be fixed.

**Comment by mastery3** [comment]
Problem `#1` at the moment is getting rid of the hack I just did with RegistryLoader.mixin.java

**Comment by Cam396** [comment]
what is the hack

**Comment by Cam396** [comment]
wait before you tell me will my braincells pack their bags and leave when they see it because of how dumb it is

**Comment by mastery3** [comment]
It's not that dumb lol, but it definitely adds a ton of problems

**Comment by Cam396** [comment]
alright what is it though

**Comment by Cam396** [comment]
like which file?

**Comment by mastery3** [comment]
src/main/java/mastery3/sharpness6/mixin/RegistryLoader.mixin.java

**Comment by mastery3** [comment]
I'm trying to get it to a `@Inject(at = @At(value = "INVOKE"), ...)` that only adds the code between `// Start of injection` and `// End of injection` without overwriting the entire function, but attempting that somehow causes a Critical Injection Error

**Comment by Cam396** [comment]
hmm will test but i have to go to bed

**Comment by mastery3** [comment]
The problems that the hack imposes is that it denies compatibility with any other mods that need to change that function

**Comment by Cam396** [comment]
how does it violate copyright

**Comment by mastery3** [comment]
Stealing Minecraft decompiled code

**Comment by mastery3** [comment]
We should probably delete this part of the conversation before I get into legal trouble

**Comment by Cam396** [comment]
yeah so thats a interesting method of doing it but whatever works works ig

**Comment by mastery3** [comment]
See if you can figure out why the Critical Injection Errors occur

**Comment by Cam396** [comment]
ok

**Comment by Cam396** [comment]
ima sleep now

**Comment by mastery3** [comment]
see you tomorrow

**Comment by sternschnaube** [comment]
Looking forward to the update - thank you! 😄

**Comment by mastery3** [comment]
Update is almost done. Last problem is figuring out how to conditionally edit `minecraft:unbreaking` without getting the original `minecraft:unbreaking` deleted when the condition is not satisfied. (Yes, `fabric:load_conditions` is that dumb.)

**Comment by mastery3** [comment]
Update is done
