### ISSUE TITLE
Doesn't seem to work in 1.21

### ISSUE THREAD

**Issue by K0KE11** [mastery3/sharpness6#13]
Just downloaded the latest version Sharpness VI 1.21-1 but it doesn't seem to work I combined 2 sharpness 5 books but they just kept being level 5 and i also tried adding another sharpness 5 book to an already sharp 5 sword and didn't work either

**Comment by mastery3** [comment]
Did you try editing the config?

**Comment by mastery3** [comment]
There should be a line in `[MINECRAFT DIRECTORY]/config/sharpness6.json` that says:
`"sharpness": 5,`
Edit the 5 to what you want the maximum level of Sharpness to be.

**Comment by K0KE11** [comment]
O damn yeah thank you so much!

**Comment by mastery3** [comment]
I've put the info in the mod description in case anyone else has this issue.
