### ISSUE TITLE
Update to 1.18.2 and beyond?

### ISSUE THREAD

**Issue by astridos2go** [mastery3/sharpness6#2]
Hi, I think this mod would be perfect for a vanilla-ish server I'm running, but it's currently on 1.18.2, and eventually will be moved to 1.19.X, while the latest version of this mod is listed as for 1.17.

On Modrinth, your FAQ says that it would be very easy for you to port to new versions, so I was wondering if you were planning on releasing new versions for the newer version of Minecraft, or if the mod just still works on these newer versions?

Thank you!

**Comment by ghost** [comment]
Hello, I would also love to see a version for 1.19.
Greetings.

**Comment by mastery3** [comment]
I was inactive for a while, but I am currently creating a 1.19 port of the mod (something changed with the `shouldPreventDamage ` method and the decompiled Minecraft source code isn't picking it up). In the meantime, there is a fork of this mod that supports 1.18.2 (not 1.19): https://github.com/Falaxir/sharpness6 (Edit: the referenced link is now outdated)

**Comment by ghost** [comment]
Awesome - looking forward to the 1.19 version 🥰

**Comment by mastery3** [comment]
Uploaded 1.19 version

**Comment by mastery3** [comment]
For some reason Minecraft stopped using `java.util.Random` and used their own `net.minecraft.util.math.random.Random`. No idea why the decompiler didn't pick that up though, might be something wrong with it (either that or I didn't read the source code properly).

**Comment by mastery3** [comment]
Nothing wrong with the decompiler, turns out someone did this change near the top, which is nowhere near the `shouldPreventDamage` method:
```diff
- import java.util.Random;
+ import net.minecraft.util.math.random.Random;

... 28 lines ...

public static boolean shouldPreventDamage(ItemStack item, int level, Random random) {
```

**Comment by ghost** [comment]
Thank you for this super fast update - I will use the mod later:)
