### ISSUE TITLE
[Feature Request] Add setting to prevent players from combining books/items' enchantments

### ISSUE THREAD

**Issue by elhertz** [mastery3/sharpness6#3]
Hey. I've been looking for a mod that would let me enchant items using books with levels higher than vanilla.
I plan to add these books to mob loot and chest loot tables.
I don't want players to be able to combine books or items to get a level higher than vanilla, that's cheating lol. I only want players to be able to enchant items with the books you can find by killing mobs or looting chests. (normal vanilla enchantment combining should still work, higher levels than that should not)
Hope you like my suggestion. Thanks!

**Comment by mastery3** [comment]
A mod named "Charm" implements what you are asking for: https://www.curseforge.com/minecraft/mc-mods/charm (note that it implements plenty of other stuff that you may not want) [not sure if it works on 1.19.1, you may have to compile the 1.19.x branch from source]

I believe that this feature request is out of scope for this mod (I might add it anyway, but not at the moment) and would require completely different code than what this mod is aiming to do.
