### ISSUE TITLE
Applying high level enchanted book traded from villager doesn't require the right amount of exp

### ISSUE THREAD

**Issue by duynh03** [mastery3/sharpness6#4]
When trading with a villager to get a high level enchanted book, for example Sharpness 18, the exp it'll cost to apply the book on an anvil is only about 28 exp levels instead of however much it should've been if you combine two sharpness 17 books together. Trading with villager also only cost 64 emerald no matter what level the enchant is when the enchant level is above the vanilla cap.

**Comment by Cam396** [comment]
This is a minecraft issue I believe, as without an extensive overhaul of all of his code this wont get fixed.

**Comment by mastery3** [comment]
Closing as the issue described is behavior intended by the Minecraft developers. Villagers shouldn't be able to trade Sharpness 18 books in the first place, but that's a separate bug.
